# Generated by Django 2.2.4 on 2019-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ['orden', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='orden',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
