# Generated by Django 2.2.4 on 2019-08-26 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_auto_20190826_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
